file:
  path: Files

spring:
  datasource:
    url: jdbc:postgresql://localhost:5252/db_data
    username: postgres
    password: 123

  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/db.changelog-1.sql




